config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'
  resources :projects do
    resources :pledges
  end
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  AMOUNT_LEVELS = [25.00, 50.00, 100.00, 200.00, 500.00]

  validates :name, :email, presence: true
  validates :amount, inclusion: { in: AMOUNT_LEVELS, message: 'was not picked' }
  validates :email, format:
    {
      with: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i
    }

  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :name, :description, presence: true
  validates :description, length: { maximum: 500 }
  validates :target_pledge_amount, numericality: { greater_than: 0 }
  validates :website, allow_blank: true, format:
    {
      with: /htt(p|ps)(:\/\/(?:www\.|(?!www))[^\s\.]+\.[^\s]{2,}|www\.[^\s]+\.[^\s]{2,})/i,
      message: 'must be valid'
    }
  validates :image_file_name, allow_blank: true, format:
    {
      with: /\w+\.(gif|jpg|png)\z/i,
      message: 'must reference a GIF, JPG, or PNG image'
    }

  has_many :pledges, dependent: :destroy

  def self.active
    where('pledging_ends_on >= ?', Time.now)
      .order(pledging_ends_on: :asc).order(target_pledge_amount: :desc)
  end

  def ended?
    pledging_ends_on.blank? || pledging_ends_on < Time.now
  end

  def total_amount_pledged
    pledges.sum(:amount)
  end

  def amount_outstanding
    target_pledge_amount - total_amount_pledged
  end

  def funded?
    target_pledge_amount <= total_amount_pledged
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @pledges = @project.pledges
  end

  def new
    @project = Project.find(params[:project_id])
    @pledge = @project.pledges.new
  end

  def create
    @project = Project.find(params[:project_id])
    @pledge = @project.pledges.new(pledge_params)
    if @pledge.save
      redirect_to project_pledges_path(@project), notice: 'Thanks for Pledging!'
    else
      render :new
    end
  end

  private

  def pledge_params
    params.require(:pledge).permit(:name, :email, :amount, :comment)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.active
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    # fail
    @project = Project.find(params[:id])
    if @project.update(allowed_params)
      redirect_to project_path(@project), notice: 'Project Successfully Updated!'
    else
      render :edit
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(allowed_params)
    if @project.save
      redirect_to project_path(@project), notice: 'Project Successfully Created!'
    else
      render :edit
    end
  end

  def destroy
    project = Project.find(params[:id])
    project.destroy
    redirect_to projects_path, alert: 'Project Successfully Deleted!'
  end

  private

  def allowed_params
    params.require(:project).permit(
      :name,
      :description,
      :target_pledge_amount,
      :website,
      :pledging_ends_on,
      :team_members,
      :image_file_name
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def format_date(project)
    if project.ended?
      content_tag :strong, 'All Done!'
    else
      "#{distance_of_time_in_words(Time.now, project.pledging_ends_on)} remaining"
    end
  end

  def image_for(project)
    if project.image_file_name.blank?
      image_tag('placeholder.png')
    else
      image_tag(project.image_file_name)
    end
  end

  def format_pledge_link(project)
    if project.funded?
      content_tag :h2, 'Funded'
    else
      link_to new_project_pledge_path(project), class: 'button ok' do
        tag1 = content_tag :h3, 'Pledge!', class: 'title'
        tag2 = content_tag :span, "Only #{number_to_currency(project.amount_outstanding)} left!", class: 'subtitle'
        (tag1 + tag2).html_safe
      end
    end
  end
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, val| %>
    <%= content_tag :p, val, class: "flash #{key}"  %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
    <p> Copyright &copy; <%= Time.now.year %> </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
    <div id="masthead">
        <h1><%= link_to 'Crowdfund', root_path %></h1>
    </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
    <nav>
        <ul>
            <li class="all-projects"><%= link_to 'All Projects', projects_path, class: 'button'%></li>
            <li class="create-project"><%= link_to 'Add New Project', new_project_path, class: 'button' %></li>
        </ul>
    </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfund - Fund stuff!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>

    <div id="wrapper">
        <%= render 'layouts/flashes' %>
        <div id="container">
            <%= render 'layouts/sidebar' %>
            <section id="content">
                <%= yield %>
            </section>
        </div>
    </div>

    <%= render 'layouts/footer' %>
</body>
</html>

app/views/pledges/index.html.erb
<header id="content-header">
    <h1>Pledges for <%= link_to @project.name, @project%></h1>
</header>

<ol id="pledges">
    <% @pledges.each do |p| %>
        <li>
            <%= mail_to(p.email, p.name) %> pledged
            <span class="amount"><%= number_to_currency(p.amount) %></span>
            (<span class="date"><%= time_ago_in_words(p.created_at) %> ago<span>)
                <p>
                    &quot;<%= p.comment %>&quot;
                </p>
        </li>
    <% end %>
</ol>

app/views/pledges/new.html.erb
<header>
    <h1>Pledge for <%= link_to @project.name, @project %></h1>
</header>

<%= form_for [@project, @pledge] do |f| %>
    <fieldset>
        <%= render 'shared/errors', object: @pledge %>
        <ol>
            <li class="required">
                <%= f.label :name %>
                <%= f.text_field :name %>
            </li>
            <li class="required">
                <%= f.label :email %>
                <%= f.text_field :email %>
            </li class="required">
            <li class="required">
                <%= f.label :amount %>
                <%= f.select :amount, Pledge::AMOUNT_LEVELS, prompt: 'Pick One' %>
            </li>
            <li>
                <%= f.label :comment %>
                <%= f.text_area :comment %>
            </li>
        </ol>
        <p>
            <%= f.submit %>
            <%= link_to 'Cancel', project_path(@project), class: 'button' %>
        </p>
    </fieldset>
<% end %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
    <%= render 'shared/errors', object: @project %>
    <fieldset>
        <ol>
            <li class="required">
                <%= f.label :name %>
                <%= f.text_field :name, autofocus: true %>
            </li>
            <li class="required">
                <%= f.label :description %>
                <%= f.text_area :description, rows: 5, cols: 31 %>
            </li>
            <li class="required">
                <%= f.label :pledging_ends_on %>
                <%= f.date_select :pledging_ends_on %>
            </li>
            <li class="required">
                <%= f.label :target_pledge_amount %>
                <%= f.number_field :target_pledge_amount %>
            </li>
            <li class="required">
                <%= f.label :website %>
                <%= f.text_field :website %>
            </li>
            <li class="required">
                <%= f.label :team_members %>
                <%= f.text_field :team_members %>
            </li>
            <li class="required">
                <%= f.label :image_file_name %>
                <%= f.text_field :image_file_name, size: 30, placeholder: 'GIF, JPG, or PNG file name' %>
            </li>
        </ol>
        <p>
            <%= f.submit %>
            <%= link_to 'Cancel', projects_path, class: 'button' %>
        </p>
    </fieldset>
<% end %>

app/views/projects/edit.html.erb
<header id="content-header">
    <h1>Edit Project: <%= @project.name %></h1>
</header>

<%= render 'form' %>

app/views/projects/index.html.erb
<ul id="projects">
    <% @projects.each do |project| %>
        <li>
            <article class="project" id="<%= dom_id(project) %> ">
                <header>
                    <%= image_for(project) %>
                    <h2><%= link_to project.name, project_path(project) %></h2>
                </header>
                <p>
                    <%= truncate(project.description, length: 150, separator: ' ') %>
                </p>
                <table>
                    <tr>
                        <td>Pledging Ends</td>
                        <td><%= format_date(project) %></td>
                    </tr>
                    <tr>
                        <td>Target Amount</td>
                        <td><%= number_to_currency(project.target_pledge_amount) %></td>
                    </tr>
                </table>
            </article>
        </li>
    <% end %>
</ul>

<p><%= pluralize(@projects.count, 'Project') %></p>

app/views/projects/new.html.erb
<header id="content-header">
    <h1>Add New Project</h1>
</header>

<%= render 'form' %>

app/views/projects/show.html.erb
<article id="project" class="project">
    <header>
        <%= image_for @project %>
        <h1><%= @project.name %></h1>
        <h2><%= format_date(@project) %></h2>
    </header>

    <p><%= @project.description %></p>

    <h3>Traget Pledge Amount</h3>
    <p><%= number_to_currency(@project.target_pledge_amount) %></p>

    <h3>Website</h3>
    <p><%= @project.website %></p>

    <h3>Team Members</h3>
    <p><%= @project.team_members %></p>

    <footer>
        <%= format_pledge_link(@project) %>
        <nav>
            <%= link_to 'Edit Project', edit_project_path, class: 'button' %>
            <%= link_to 'Delete Project', project_path(@project),
                class: 'button',
                method: :delete, data: {confirm: 'Are you sure you want to delete this project?'} %>
            <%= link_to pluralize(@project.pledges.count, 'Pledge'), project_pledges_path(@project), class: 'button' %>
        </nav>
    </footer>
</article>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.titleize.downcase %> could not be saved.
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>